[2023-11-20T08:38:36.288+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-20T08:38:36.295+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-20T08:38:36.295+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:38:36.314+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-02 00:00:00+00:00
[2023-11-20T08:38:36.328+0000] {standard_task_runner.py:57} INFO - Started process 75 to run task
[2023-11-20T08:38:36.334+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-02T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmppihgyfb8']
[2023-11-20T08:38:36.346+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask retrieve_data
[2023-11-20T08:38:36.428+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-02T00:00:00+00:00 [running]> on host 74ca1234e792
[2023-11-20T08:38:36.511+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-02T00:00:00+00:00'
[2023-11-20T08:38:36.518+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Scripts/etl.py", line 18, in retrieve_data
    aws_access_key_id=YOUR_ACCESS_KEY,
NameError: name 'YOUR_ACCESS_KEY' is not defined
[2023-11-20T08:38:36.530+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231102T000000, start_date=20231120T083836, end_date=20231120T083836
[2023-11-20T08:38:36.561+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task retrieve_data (name 'YOUR_ACCESS_KEY' is not defined; 75)
[2023-11-20T08:38:36.598+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-20T08:38:36.624+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:43:23.096+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-20T08:43:23.104+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-20T08:43:23.106+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:43:23.127+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-02 00:00:00+00:00
[2023-11-20T08:43:23.135+0000] {standard_task_runner.py:57} INFO - Started process 76 to run task
[2023-11-20T08:43:23.140+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-02T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpm18owevk']
[2023-11-20T08:43:23.150+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask retrieve_data
[2023-11-20T08:43:23.247+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-02T00:00:00+00:00 [running]> on host c84b35a13244
[2023-11-20T08:43:23.316+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-02T00:00:00+00:00'
[2023-11-20T08:43:25.928+0000] {etl.py:60} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T08:43:25.930+0000] {etl.py:64} INFO - Uploading data to 'raw_data'...
[2023-11-20T08:43:26.082+0000] {etl.py:71} INFO - Updating 'Old_Data' with current data...
[2023-11-20T08:43:27.213+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:43:27.295+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231102T000000, start_date=20231120T084323, end_date=20231120T084327
[2023-11-20T08:43:27.429+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:43:27.487+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:46:36.621+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-20T08:46:36.637+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-20T08:46:36.642+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:46:36.668+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-02 00:00:00+00:00
[2023-11-20T08:46:36.683+0000] {standard_task_runner.py:57} INFO - Started process 90 to run task
[2023-11-20T08:46:36.700+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-02T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpcqqv6365']
[2023-11-20T08:46:36.707+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask retrieve_data
[2023-11-20T08:46:36.820+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-02T00:00:00+00:00 [running]> on host d26cbef9e8ab
[2023-11-20T08:46:36.910+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-02T00:00:00+00:00'
[2023-11-20T08:46:39.244+0000] {etl.py:62} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T08:46:39.246+0000] {etl.py:66} INFO - Uploading data to 'raw_data'...
[2023-11-20T08:46:39.418+0000] {etl.py:73} INFO - Updating 'Old_Data' with current data...
[2023-11-20T08:46:39.967+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:46:39.974+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231102T000000, start_date=20231120T084636, end_date=20231120T084639
[2023-11-20T08:46:40.003+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:46:40.029+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:50:16.754+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-20T08:50:16.773+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-20T08:50:16.773+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:50:16.809+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-02 00:00:00+00:00
[2023-11-20T08:50:16.817+0000] {standard_task_runner.py:57} INFO - Started process 82 to run task
[2023-11-20T08:50:16.846+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-02T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp6_x6i70c']
[2023-11-20T08:50:16.853+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask retrieve_data
[2023-11-20T08:50:16.995+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-02T00:00:00+00:00 [running]> on host 3ef39241d6e6
[2023-11-20T08:50:17.129+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-02T00:00:00+00:00'
[2023-11-20T08:50:19.755+0000] {etl.py:87} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T08:50:19.758+0000] {etl.py:91} INFO - Uploading data to 'raw_data'...
[2023-11-20T08:50:19.897+0000] {etl.py:98} INFO - Updating 'Old_Data' with current data...
[2023-11-20T08:50:21.161+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:50:21.220+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231102T000000, start_date=20231120T085016, end_date=20231120T085021
[2023-11-20T08:50:21.283+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:50:21.469+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-20T22:32:24.572+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-20T22:32:24.604+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-20T22:32:24.616+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T22:32:24.660+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-02 00:00:00+00:00
[2023-11-20T22:32:24.681+0000] {standard_task_runner.py:57} INFO - Started process 90 to run task
[2023-11-20T22:32:24.706+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-02T00:00:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpr6nkevjc']
[2023-11-20T22:32:24.742+0000] {standard_task_runner.py:85} INFO - Job 76: Subtask retrieve_data
[2023-11-20T22:32:24.906+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-02T00:00:00+00:00 [running]> on host ad6c889005f6
[2023-11-20T22:32:25.257+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-02T00:00:00+00:00'
[2023-11-20T22:32:28.415+0000] {etl.py:87} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T22:32:28.418+0000] {etl.py:91} INFO - Uploading data to 'raw_data'...
[2023-11-20T22:32:28.576+0000] {etl.py:98} INFO - Updating 'Old_Data' with current data...
[2023-11-20T22:32:32.011+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T22:32:32.137+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231102T000000, start_date=20231120T223224, end_date=20231120T223232
[2023-11-20T22:32:32.398+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T22:32:32.500+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T22:45:55.206+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-20T22:45:55.274+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-20T22:45:55.280+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T22:45:55.307+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-02 00:00:00+00:00
[2023-11-20T22:45:55.318+0000] {standard_task_runner.py:57} INFO - Started process 93 to run task
[2023-11-20T22:45:55.393+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-02T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpikcsqvi0']
[2023-11-20T22:45:55.422+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask retrieve_data
[2023-11-20T22:45:55.683+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-02T00:00:00+00:00 [running]> on host e1d2c8bc7439
[2023-11-20T22:45:55.891+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-02T00:00:00+00:00'
[2023-11-20T22:45:56.900+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Scripts/etl.py", line 60, in retrieve_data
    objects_to_delete = s3.list_objects_v2(Bucket=BUCKET_NAME, Prefix='raw_data/')
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
[2023-11-20T22:45:56.970+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231102T000000, start_date=20231120T224555, end_date=20231120T224556
[2023-11-20T22:45:57.013+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 11 for task retrieve_data (An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist; 93)
[2023-11-20T22:45:57.055+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-20T22:45:57.137+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-20T22:47:34.000+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-20T22:47:34.023+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-02T00:00:00+00:00 [queued]>
[2023-11-20T22:47:34.025+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T22:47:34.089+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-02 00:00:00+00:00
[2023-11-20T22:47:34.115+0000] {standard_task_runner.py:57} INFO - Started process 90 to run task
[2023-11-20T22:47:34.158+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-02T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp53morl_u']
[2023-11-20T22:47:34.190+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask retrieve_data
[2023-11-20T22:47:34.416+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-02T00:00:00+00:00 [running]> on host fda681cc78c9
[2023-11-20T22:47:34.626+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-02T00:00:00+00:00'
[2023-11-20T22:47:36.847+0000] {etl.py:91} INFO - Uploading data to 'raw_data'...
[2023-11-20T22:47:43.622+0000] {etl.py:98} INFO - Updating 'Old_Data' with current data...
[2023-11-20T22:47:44.362+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T22:47:44.488+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231102T000000, start_date=20231120T224734, end_date=20231120T224744
[2023-11-20T22:47:44.574+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T22:47:44.651+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
