[2023-11-20T08:38:37.249+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-20T08:38:37.255+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-20T08:38:37.256+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:38:37.301+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-12 00:00:00+00:00
[2023-11-20T08:38:37.305+0000] {standard_task_runner.py:57} INFO - Started process 99 to run task
[2023-11-20T08:38:37.308+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-12T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpj25p3t2i']
[2023-11-20T08:38:37.311+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask retrieve_data
[2023-11-20T08:38:37.341+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-12T00:00:00+00:00 [running]> on host 74ca1234e792
[2023-11-20T08:38:37.380+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-12T00:00:00+00:00'
[2023-11-20T08:38:37.381+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Scripts/etl.py", line 18, in retrieve_data
    aws_access_key_id=YOUR_ACCESS_KEY,
NameError: name 'YOUR_ACCESS_KEY' is not defined
[2023-11-20T08:38:37.386+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231112T000000, start_date=20231120T083837, end_date=20231120T083837
[2023-11-20T08:38:37.391+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task retrieve_data (name 'YOUR_ACCESS_KEY' is not defined; 99)
[2023-11-20T08:38:37.400+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-20T08:38:37.415+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:43:24.178+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-20T08:43:24.186+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-20T08:43:24.187+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:43:24.226+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-12 00:00:00+00:00
[2023-11-20T08:43:24.231+0000] {standard_task_runner.py:57} INFO - Started process 98 to run task
[2023-11-20T08:43:24.238+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-12T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp4nzd_8ed']
[2023-11-20T08:43:24.244+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask retrieve_data
[2023-11-20T08:43:24.278+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-12T00:00:00+00:00 [running]> on host c84b35a13244
[2023-11-20T08:43:24.321+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-12T00:00:00+00:00'
[2023-11-20T08:43:25.531+0000] {etl.py:60} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T08:43:25.531+0000] {etl.py:64} INFO - Uploading data to 'raw_data'...
[2023-11-20T08:43:25.675+0000] {etl.py:71} INFO - Updating 'Old_Data' with current data...
[2023-11-20T08:43:26.082+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:43:26.087+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231112T000000, start_date=20231120T084324, end_date=20231120T084326
[2023-11-20T08:43:26.112+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:43:26.128+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:46:37.555+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-20T08:46:37.564+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-20T08:46:37.564+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:46:37.611+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-12 00:00:00+00:00
[2023-11-20T08:46:37.616+0000] {standard_task_runner.py:57} INFO - Started process 106 to run task
[2023-11-20T08:46:37.620+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-12T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpfs7uo6_m']
[2023-11-20T08:46:37.624+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask retrieve_data
[2023-11-20T08:46:37.676+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-12T00:00:00+00:00 [running]> on host d26cbef9e8ab
[2023-11-20T08:46:37.731+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-12T00:00:00+00:00'
[2023-11-20T08:46:39.303+0000] {etl.py:62} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T08:46:39.304+0000] {etl.py:66} INFO - Uploading data to 'raw_data'...
[2023-11-20T08:46:39.497+0000] {etl.py:73} INFO - Updating 'Old_Data' with current data...
[2023-11-20T08:46:40.103+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:46:40.108+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231112T000000, start_date=20231120T084637, end_date=20231120T084640
[2023-11-20T08:46:40.136+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:46:40.151+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:50:17.638+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-20T08:50:17.650+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-20T08:50:17.651+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:50:17.664+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-12 00:00:00+00:00
[2023-11-20T08:50:17.669+0000] {standard_task_runner.py:57} INFO - Started process 97 to run task
[2023-11-20T08:50:17.679+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-12T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmplq3pj3gu']
[2023-11-20T08:50:17.684+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask retrieve_data
[2023-11-20T08:50:17.736+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-12T00:00:00+00:00 [running]> on host 3ef39241d6e6
[2023-11-20T08:50:17.791+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-12T00:00:00+00:00'
[2023-11-20T08:50:19.037+0000] {etl.py:87} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T08:50:19.038+0000] {etl.py:91} INFO - Uploading data to 'raw_data'...
[2023-11-20T08:50:19.181+0000] {etl.py:98} INFO - Updating 'Old_Data' with current data...
[2023-11-20T08:50:22.401+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:50:22.413+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231112T000000, start_date=20231120T085017, end_date=20231120T085022
[2023-11-20T08:50:22.436+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:50:22.457+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T22:32:26.557+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-20T22:32:26.568+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-20T22:32:26.568+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T22:32:26.578+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-12 00:00:00+00:00
[2023-11-20T22:32:26.591+0000] {standard_task_runner.py:57} INFO - Started process 105 to run task
[2023-11-20T22:32:26.608+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-12T00:00:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpnl_m4u7o']
[2023-11-20T22:32:26.630+0000] {standard_task_runner.py:85} INFO - Job 81: Subtask retrieve_data
[2023-11-20T22:32:26.694+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-12T00:00:00+00:00 [running]> on host ad6c889005f6
[2023-11-20T22:32:26.797+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-12T00:00:00+00:00'
[2023-11-20T22:32:28.483+0000] {etl.py:87} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T22:32:28.491+0000] {etl.py:91} INFO - Uploading data to 'raw_data'...
[2023-11-20T22:32:28.653+0000] {etl.py:98} INFO - Updating 'Old_Data' with current data...
[2023-11-20T22:32:32.134+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T22:32:32.228+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231112T000000, start_date=20231120T223226, end_date=20231120T223232
[2023-11-20T22:32:32.416+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T22:32:32.476+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T22:45:57.053+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-20T22:45:57.066+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-20T22:45:57.084+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T22:45:57.191+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-12 00:00:00+00:00
[2023-11-20T22:45:57.230+0000] {standard_task_runner.py:57} INFO - Started process 107 to run task
[2023-11-20T22:45:57.244+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-12T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpad1zndpu']
[2023-11-20T22:45:57.267+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask retrieve_data
[2023-11-20T22:45:57.463+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-12T00:00:00+00:00 [running]> on host e1d2c8bc7439
[2023-11-20T22:45:57.633+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-12T00:00:00+00:00'
[2023-11-20T22:45:58.090+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Scripts/etl.py", line 60, in retrieve_data
    objects_to_delete = s3.list_objects_v2(Bucket=BUCKET_NAME, Prefix='raw_data/')
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
[2023-11-20T22:45:58.098+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231112T000000, start_date=20231120T224557, end_date=20231120T224558
[2023-11-20T22:45:58.106+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 15 for task retrieve_data (An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist; 107)
[2023-11-20T22:45:58.134+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-20T22:45:58.155+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-20T22:47:35.990+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-20T22:47:36.006+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-12T00:00:00+00:00 [queued]>
[2023-11-20T22:47:36.007+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T22:47:36.027+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-12 00:00:00+00:00
[2023-11-20T22:47:36.035+0000] {standard_task_runner.py:57} INFO - Started process 104 to run task
[2023-11-20T22:47:36.042+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-12T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp3ap2ieie']
[2023-11-20T22:47:36.048+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask retrieve_data
[2023-11-20T22:47:36.135+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-12T00:00:00+00:00 [running]> on host fda681cc78c9
[2023-11-20T22:47:36.226+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-12T00:00:00+00:00'
[2023-11-20T22:47:37.818+0000] {etl.py:91} INFO - Uploading data to 'raw_data'...
[2023-11-20T22:47:41.182+0000] {etl.py:98} INFO - Updating 'Old_Data' with current data...
[2023-11-20T22:47:41.883+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T22:47:41.917+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231112T000000, start_date=20231120T224735, end_date=20231120T224741
[2023-11-20T22:47:42.094+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T22:47:42.121+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
