[2023-11-20T08:38:37.393+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-20T08:38:37.399+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-20T08:38:37.400+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:38:37.409+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-14 00:00:00+00:00
[2023-11-20T08:38:37.412+0000] {standard_task_runner.py:57} INFO - Started process 101 to run task
[2023-11-20T08:38:37.414+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-14T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpxtopy_ru']
[2023-11-20T08:38:37.417+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask retrieve_data
[2023-11-20T08:38:37.443+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-14T00:00:00+00:00 [running]> on host 74ca1234e792
[2023-11-20T08:38:37.475+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-14T00:00:00+00:00'
[2023-11-20T08:38:37.476+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Scripts/etl.py", line 18, in retrieve_data
    aws_access_key_id=YOUR_ACCESS_KEY,
NameError: name 'YOUR_ACCESS_KEY' is not defined
[2023-11-20T08:38:37.480+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231114T000000, start_date=20231120T083837, end_date=20231120T083837
[2023-11-20T08:38:37.484+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 16 for task retrieve_data (name 'YOUR_ACCESS_KEY' is not defined; 101)
[2023-11-20T08:38:37.508+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-20T08:38:37.520+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:43:24.435+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-20T08:43:24.440+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-20T08:43:24.441+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:43:24.447+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-14 00:00:00+00:00
[2023-11-20T08:43:24.451+0000] {standard_task_runner.py:57} INFO - Started process 101 to run task
[2023-11-20T08:43:24.454+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-14T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpk9td6euy']
[2023-11-20T08:43:24.456+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask retrieve_data
[2023-11-20T08:43:24.505+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-14T00:00:00+00:00 [running]> on host c84b35a13244
[2023-11-20T08:43:24.544+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-14T00:00:00+00:00'
[2023-11-20T08:43:25.782+0000] {etl.py:60} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T08:43:25.783+0000] {etl.py:64} INFO - Uploading data to 'raw_data'...
[2023-11-20T08:43:25.942+0000] {etl.py:71} INFO - Updating 'Old_Data' with current data...
[2023-11-20T08:43:26.361+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:43:26.366+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231114T000000, start_date=20231120T084324, end_date=20231120T084326
[2023-11-20T08:43:26.392+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:43:26.420+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:46:37.836+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-20T08:46:37.840+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-20T08:46:37.840+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:46:37.845+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-14 00:00:00+00:00
[2023-11-20T08:46:37.856+0000] {standard_task_runner.py:57} INFO - Started process 109 to run task
[2023-11-20T08:46:37.860+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-14T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp14pd823a']
[2023-11-20T08:46:37.862+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask retrieve_data
[2023-11-20T08:46:37.903+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-14T00:00:00+00:00 [running]> on host d26cbef9e8ab
[2023-11-20T08:46:37.942+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-14T00:00:00+00:00'
[2023-11-20T08:46:39.807+0000] {etl.py:62} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T08:46:39.808+0000] {etl.py:66} INFO - Uploading data to 'raw_data'...
[2023-11-20T08:46:40.027+0000] {etl.py:73} INFO - Updating 'Old_Data' with current data...
[2023-11-20T08:46:40.468+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:46:40.475+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231114T000000, start_date=20231120T084637, end_date=20231120T084640
[2023-11-20T08:46:40.492+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:46:40.508+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:50:17.948+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-20T08:50:17.952+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-20T08:50:17.952+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:50:17.958+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-14 00:00:00+00:00
[2023-11-20T08:50:17.961+0000] {standard_task_runner.py:57} INFO - Started process 101 to run task
[2023-11-20T08:50:17.964+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-14T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmphr6fmp8h']
[2023-11-20T08:50:17.968+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask retrieve_data
[2023-11-20T08:50:18.004+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-14T00:00:00+00:00 [running]> on host 3ef39241d6e6
[2023-11-20T08:50:18.041+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-14T00:00:00+00:00'
[2023-11-20T08:50:19.340+0000] {etl.py:87} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T08:50:19.341+0000] {etl.py:91} INFO - Uploading data to 'raw_data'...
[2023-11-20T08:50:19.483+0000] {etl.py:98} INFO - Updating 'Old_Data' with current data...
[2023-11-20T08:50:20.492+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:50:20.505+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231114T000000, start_date=20231120T085017, end_date=20231120T085020
[2023-11-20T08:50:20.549+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:50:20.579+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T22:32:26.953+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-20T22:32:26.961+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-20T22:32:26.962+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T22:32:26.973+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-14 00:00:00+00:00
[2023-11-20T22:32:26.982+0000] {standard_task_runner.py:57} INFO - Started process 107 to run task
[2023-11-20T22:32:27.000+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-14T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpky6czbqr']
[2023-11-20T22:32:27.017+0000] {standard_task_runner.py:85} INFO - Job 83: Subtask retrieve_data
[2023-11-20T22:32:27.137+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-14T00:00:00+00:00 [running]> on host ad6c889005f6
[2023-11-20T22:32:27.227+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-14T00:00:00+00:00'
[2023-11-20T22:32:28.603+0000] {etl.py:87} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T22:32:28.606+0000] {etl.py:91} INFO - Uploading data to 'raw_data'...
[2023-11-20T22:32:28.744+0000] {etl.py:98} INFO - Updating 'Old_Data' with current data...
[2023-11-20T22:32:29.864+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T22:32:29.887+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231114T000000, start_date=20231120T223226, end_date=20231120T223229
[2023-11-20T22:32:29.980+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T22:32:30.074+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T22:45:57.758+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-20T22:45:57.773+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-20T22:45:57.773+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T22:45:57.786+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-14 00:00:00+00:00
[2023-11-20T22:45:57.792+0000] {standard_task_runner.py:57} INFO - Started process 108 to run task
[2023-11-20T22:45:57.796+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-14T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp04fzetno']
[2023-11-20T22:45:57.801+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask retrieve_data
[2023-11-20T22:45:57.845+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-14T00:00:00+00:00 [running]> on host e1d2c8bc7439
[2023-11-20T22:45:57.900+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-14T00:00:00+00:00'
[2023-11-20T22:45:58.294+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Scripts/etl.py", line 60, in retrieve_data
    objects_to_delete = s3.list_objects_v2(Bucket=BUCKET_NAME, Prefix='raw_data/')
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
[2023-11-20T22:45:58.302+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231114T000000, start_date=20231120T224557, end_date=20231120T224558
[2023-11-20T22:45:58.309+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task retrieve_data (An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist; 108)
[2023-11-20T22:45:58.340+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-20T22:45:58.368+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-20T22:47:36.459+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-20T22:47:36.466+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-14T00:00:00+00:00 [queued]>
[2023-11-20T22:47:36.468+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T22:47:36.479+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-14 00:00:00+00:00
[2023-11-20T22:47:36.492+0000] {standard_task_runner.py:57} INFO - Started process 107 to run task
[2023-11-20T22:47:36.502+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-14T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp9zfgkr77']
[2023-11-20T22:47:36.508+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask retrieve_data
[2023-11-20T22:47:36.611+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-14T00:00:00+00:00 [running]> on host fda681cc78c9
[2023-11-20T22:47:36.805+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-14T00:00:00+00:00'
[2023-11-20T22:47:38.642+0000] {etl.py:87} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T22:47:38.645+0000] {etl.py:91} INFO - Uploading data to 'raw_data'...
[2023-11-20T22:47:38.814+0000] {etl.py:98} INFO - Updating 'Old_Data' with current data...
[2023-11-20T22:47:40.124+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T22:47:40.161+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231114T000000, start_date=20231120T224736, end_date=20231120T224740
[2023-11-20T22:47:40.264+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T22:47:40.323+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
