[2023-11-20T08:38:36.841+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-20T08:38:36.848+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-20T08:38:36.849+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:38:36.886+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-09 00:00:00+00:00
[2023-11-20T08:38:36.890+0000] {standard_task_runner.py:57} INFO - Started process 90 to run task
[2023-11-20T08:38:36.892+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-09T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp_z4azz4b']
[2023-11-20T08:38:36.896+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask retrieve_data
[2023-11-20T08:38:36.934+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-09T00:00:00+00:00 [running]> on host 74ca1234e792
[2023-11-20T08:38:36.983+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-09T00:00:00+00:00'
[2023-11-20T08:38:36.985+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Scripts/etl.py", line 18, in retrieve_data
    aws_access_key_id=YOUR_ACCESS_KEY,
NameError: name 'YOUR_ACCESS_KEY' is not defined
[2023-11-20T08:38:36.991+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231109T000000, start_date=20231120T083836, end_date=20231120T083836
[2023-11-20T08:38:36.997+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 11 for task retrieve_data (name 'YOUR_ACCESS_KEY' is not defined; 90)
[2023-11-20T08:38:37.025+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-20T08:38:37.045+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:43:23.687+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-20T08:43:23.696+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-20T08:43:23.696+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:43:23.709+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-09 00:00:00+00:00
[2023-11-20T08:43:23.723+0000] {standard_task_runner.py:57} INFO - Started process 89 to run task
[2023-11-20T08:43:23.726+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-09T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp0ugcz946']
[2023-11-20T08:43:23.732+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask retrieve_data
[2023-11-20T08:43:23.783+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-09T00:00:00+00:00 [running]> on host c84b35a13244
[2023-11-20T08:43:23.876+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-09T00:00:00+00:00'
[2023-11-20T08:43:25.142+0000] {etl.py:60} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T08:43:25.142+0000] {etl.py:64} INFO - Uploading data to 'raw_data'...
[2023-11-20T08:43:25.302+0000] {etl.py:71} INFO - Updating 'Old_Data' with current data...
[2023-11-20T08:43:25.705+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:43:25.713+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231109T000000, start_date=20231120T084323, end_date=20231120T084325
[2023-11-20T08:43:25.764+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:43:25.783+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:46:37.085+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-20T08:46:37.094+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-20T08:46:37.094+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:46:37.111+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-09 00:00:00+00:00
[2023-11-20T08:46:37.122+0000] {standard_task_runner.py:57} INFO - Started process 97 to run task
[2023-11-20T08:46:37.128+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-09T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp8rxdgrxw']
[2023-11-20T08:46:37.132+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask retrieve_data
[2023-11-20T08:46:37.193+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-09T00:00:00+00:00 [running]> on host d26cbef9e8ab
[2023-11-20T08:46:37.270+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-09T00:00:00+00:00'
[2023-11-20T08:46:39.546+0000] {etl.py:62} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T08:46:39.547+0000] {etl.py:66} INFO - Uploading data to 'raw_data'...
[2023-11-20T08:46:39.746+0000] {etl.py:73} INFO - Updating 'Old_Data' with current data...
[2023-11-20T08:46:42.726+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:46:42.737+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231109T000000, start_date=20231120T084637, end_date=20231120T084642
[2023-11-20T08:46:42.762+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:46:42.781+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:50:17.048+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-20T08:50:17.064+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-20T08:50:17.068+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:50:17.153+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-09 00:00:00+00:00
[2023-11-20T08:50:17.160+0000] {standard_task_runner.py:57} INFO - Started process 89 to run task
[2023-11-20T08:50:17.172+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-09T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp71yft540']
[2023-11-20T08:50:17.180+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask retrieve_data
[2023-11-20T08:50:17.257+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-09T00:00:00+00:00 [running]> on host 3ef39241d6e6
[2023-11-20T08:50:17.322+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-09T00:00:00+00:00'
[2023-11-20T08:50:18.689+0000] {etl.py:87} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T08:50:18.690+0000] {etl.py:91} INFO - Uploading data to 'raw_data'...
[2023-11-20T08:50:18.845+0000] {etl.py:98} INFO - Updating 'Old_Data' with current data...
[2023-11-20T08:50:22.039+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:50:22.052+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231109T000000, start_date=20231120T085017, end_date=20231120T085022
[2023-11-20T08:50:22.067+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:50:22.115+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T22:32:25.418+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-20T22:32:25.427+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-20T22:32:25.429+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T22:32:25.525+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-09 00:00:00+00:00
[2023-11-20T22:32:25.550+0000] {standard_task_runner.py:57} INFO - Started process 99 to run task
[2023-11-20T22:32:25.577+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-09T00:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp7sz7w9yp']
[2023-11-20T22:32:25.587+0000] {standard_task_runner.py:85} INFO - Job 78: Subtask retrieve_data
[2023-11-20T22:32:25.699+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-09T00:00:00+00:00 [running]> on host ad6c889005f6
[2023-11-20T22:32:25.832+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-09T00:00:00+00:00'
[2023-11-20T22:32:28.485+0000] {etl.py:87} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T22:32:28.494+0000] {etl.py:91} INFO - Uploading data to 'raw_data'...
[2023-11-20T22:32:28.668+0000] {etl.py:98} INFO - Updating 'Old_Data' with current data...
[2023-11-20T22:32:31.534+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T22:32:31.657+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231109T000000, start_date=20231120T223225, end_date=20231120T223231
[2023-11-20T22:32:31.853+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T22:32:31.945+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T22:45:56.206+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-20T22:45:56.218+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-20T22:45:56.226+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T22:45:56.252+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-09 00:00:00+00:00
[2023-11-20T22:45:56.264+0000] {standard_task_runner.py:57} INFO - Started process 102 to run task
[2023-11-20T22:45:56.292+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-09T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpm6dh81lo']
[2023-11-20T22:45:56.315+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask retrieve_data
[2023-11-20T22:45:56.445+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-09T00:00:00+00:00 [running]> on host e1d2c8bc7439
[2023-11-20T22:45:56.587+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-09T00:00:00+00:00'
[2023-11-20T22:45:57.156+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Scripts/etl.py", line 60, in retrieve_data
    objects_to_delete = s3.list_objects_v2(Bucket=BUCKET_NAME, Prefix='raw_data/')
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
[2023-11-20T22:45:57.229+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231109T000000, start_date=20231120T224556, end_date=20231120T224557
[2023-11-20T22:45:57.249+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 12 for task retrieve_data (An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist; 102)
[2023-11-20T22:45:57.390+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-20T22:45:57.550+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-20T22:47:35.314+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-20T22:47:35.331+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-20T22:47:35.335+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T22:47:35.374+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-09 00:00:00+00:00
[2023-11-20T22:47:35.397+0000] {standard_task_runner.py:57} INFO - Started process 100 to run task
[2023-11-20T22:47:35.406+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-09T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpkq4ny66a']
[2023-11-20T22:47:35.414+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask retrieve_data
[2023-11-20T22:47:35.511+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-09T00:00:00+00:00 [running]> on host fda681cc78c9
[2023-11-20T22:47:35.651+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-09T00:00:00+00:00'
[2023-11-20T22:47:37.310+0000] {etl.py:91} INFO - Uploading data to 'raw_data'...
[2023-11-20T22:47:42.742+0000] {etl.py:98} INFO - Updating 'Old_Data' with current data...
[2023-11-20T22:47:43.463+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T22:47:43.508+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231109T000000, start_date=20231120T224735, end_date=20231120T224743
[2023-11-20T22:47:43.571+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T22:47:43.700+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
