[2023-11-20T08:38:37.496+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-20T08:38:37.500+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-20T08:38:37.500+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:38:37.504+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-15 00:00:00+00:00
[2023-11-20T08:38:37.507+0000] {standard_task_runner.py:57} INFO - Started process 102 to run task
[2023-11-20T08:38:37.510+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-15T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp_jrth063']
[2023-11-20T08:38:37.512+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask retrieve_data
[2023-11-20T08:38:37.534+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-15T00:00:00+00:00 [running]> on host 74ca1234e792
[2023-11-20T08:38:37.565+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-15T00:00:00+00:00'
[2023-11-20T08:38:37.566+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Scripts/etl.py", line 18, in retrieve_data
    aws_access_key_id=YOUR_ACCESS_KEY,
NameError: name 'YOUR_ACCESS_KEY' is not defined
[2023-11-20T08:38:37.570+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231115T000000, start_date=20231120T083837, end_date=20231120T083837
[2023-11-20T08:38:37.574+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task retrieve_data (name 'YOUR_ACCESS_KEY' is not defined; 102)
[2023-11-20T08:38:37.603+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-20T08:38:37.614+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:43:24.551+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-20T08:43:24.556+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-20T08:43:24.556+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:43:24.562+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-15 00:00:00+00:00
[2023-11-20T08:43:24.566+0000] {standard_task_runner.py:57} INFO - Started process 102 to run task
[2023-11-20T08:43:24.569+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-15T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpuv_seoaq']
[2023-11-20T08:43:24.571+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask retrieve_data
[2023-11-20T08:43:24.613+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-15T00:00:00+00:00 [running]> on host c84b35a13244
[2023-11-20T08:43:24.651+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-15T00:00:00+00:00'
[2023-11-20T08:43:25.928+0000] {etl.py:60} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T08:43:25.930+0000] {etl.py:64} INFO - Uploading data to 'raw_data'...
[2023-11-20T08:43:27.533+0000] {etl.py:71} INFO - Updating 'Old_Data' with current data...
[2023-11-20T08:43:28.002+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:43:28.020+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231115T000000, start_date=20231120T084324, end_date=20231120T084328
[2023-11-20T08:43:28.068+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:43:28.101+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:46:37.986+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-20T08:46:37.990+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-20T08:46:37.990+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:46:37.998+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-15 00:00:00+00:00
[2023-11-20T08:46:38.004+0000] {standard_task_runner.py:57} INFO - Started process 110 to run task
[2023-11-20T08:46:38.015+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-15T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp4hea6zf0']
[2023-11-20T08:46:38.018+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask retrieve_data
[2023-11-20T08:46:38.044+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-15T00:00:00+00:00 [running]> on host d26cbef9e8ab
[2023-11-20T08:46:38.077+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-15T00:00:00+00:00'
[2023-11-20T08:46:39.554+0000] {etl.py:62} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T08:46:39.555+0000] {etl.py:66} INFO - Uploading data to 'raw_data'...
[2023-11-20T08:46:39.789+0000] {etl.py:73} INFO - Updating 'Old_Data' with current data...
[2023-11-20T08:46:40.306+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:46:40.312+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231115T000000, start_date=20231120T084637, end_date=20231120T084640
[2023-11-20T08:46:40.348+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:46:40.359+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:50:18.103+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-20T08:50:18.107+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-20T08:50:18.108+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:50:18.113+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-15 00:00:00+00:00
[2023-11-20T08:50:18.117+0000] {standard_task_runner.py:57} INFO - Started process 102 to run task
[2023-11-20T08:50:18.119+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-15T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpsw5wv6s7']
[2023-11-20T08:50:18.122+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask retrieve_data
[2023-11-20T08:50:18.182+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-15T00:00:00+00:00 [running]> on host 3ef39241d6e6
[2023-11-20T08:50:18.220+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-15T00:00:00+00:00'
[2023-11-20T08:50:19.396+0000] {etl.py:87} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T08:50:19.397+0000] {etl.py:91} INFO - Uploading data to 'raw_data'...
[2023-11-20T08:50:19.531+0000] {etl.py:98} INFO - Updating 'Old_Data' with current data...
[2023-11-20T08:50:22.534+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:50:22.543+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231115T000000, start_date=20231120T085018, end_date=20231120T085022
[2023-11-20T08:50:22.566+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:50:22.599+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T22:32:27.294+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-20T22:32:27.300+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-20T22:32:27.300+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T22:32:27.309+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-15 00:00:00+00:00
[2023-11-20T22:32:27.317+0000] {standard_task_runner.py:57} INFO - Started process 108 to run task
[2023-11-20T22:32:27.322+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-15T00:00:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp03v24yfc']
[2023-11-20T22:32:27.329+0000] {standard_task_runner.py:85} INFO - Job 84: Subtask retrieve_data
[2023-11-20T22:32:27.377+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-15T00:00:00+00:00 [running]> on host ad6c889005f6
[2023-11-20T22:32:27.466+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-15T00:00:00+00:00'
[2023-11-20T22:32:28.833+0000] {etl.py:87} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T22:32:28.834+0000] {etl.py:91} INFO - Uploading data to 'raw_data'...
[2023-11-20T22:32:28.982+0000] {etl.py:98} INFO - Updating 'Old_Data' with current data...
[2023-11-20T22:32:30.124+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T22:32:30.187+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231115T000000, start_date=20231120T223227, end_date=20231120T223230
[2023-11-20T22:32:30.259+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T22:32:30.336+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T22:45:57.758+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-20T22:45:57.773+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-20T22:45:57.773+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T22:45:57.786+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-15 00:00:00+00:00
[2023-11-20T22:45:57.792+0000] {standard_task_runner.py:57} INFO - Started process 109 to run task
[2023-11-20T22:45:57.796+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-15T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpv8lzrbbo']
[2023-11-20T22:45:57.801+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask retrieve_data
[2023-11-20T22:45:57.845+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-15T00:00:00+00:00 [running]> on host e1d2c8bc7439
[2023-11-20T22:45:57.899+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-15T00:00:00+00:00'
[2023-11-20T22:45:58.308+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Scripts/etl.py", line 60, in retrieve_data
    objects_to_delete = s3.list_objects_v2(Bucket=BUCKET_NAME, Prefix='raw_data/')
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
[2023-11-20T22:45:58.315+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231115T000000, start_date=20231120T224557, end_date=20231120T224558
[2023-11-20T22:45:58.321+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task retrieve_data (An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist; 109)
[2023-11-20T22:45:58.338+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-20T22:45:58.366+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-20T22:47:36.548+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-20T22:47:36.566+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-15T00:00:00+00:00 [queued]>
[2023-11-20T22:47:36.567+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T22:47:36.799+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-15 00:00:00+00:00
[2023-11-20T22:47:36.818+0000] {standard_task_runner.py:57} INFO - Started process 108 to run task
[2023-11-20T22:47:36.846+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-15T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpy8fibw3p']
[2023-11-20T22:47:36.858+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask retrieve_data
[2023-11-20T22:47:36.975+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-15T00:00:00+00:00 [running]> on host fda681cc78c9
[2023-11-20T22:47:37.112+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-15T00:00:00+00:00'
[2023-11-20T22:47:39.154+0000] {etl.py:87} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T22:47:39.157+0000] {etl.py:91} INFO - Uploading data to 'raw_data'...
[2023-11-20T22:47:39.327+0000] {etl.py:98} INFO - Updating 'Old_Data' with current data...
[2023-11-20T22:47:40.515+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T22:47:40.554+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231115T000000, start_date=20231120T224736, end_date=20231120T224740
[2023-11-20T22:47:40.584+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T22:47:40.644+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
