[2023-11-20T08:38:36.290+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-20T08:38:36.296+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-20T08:38:36.296+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:38:36.312+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-07 00:00:00+00:00
[2023-11-20T08:38:36.331+0000] {standard_task_runner.py:57} INFO - Started process 76 to run task
[2023-11-20T08:38:36.346+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-07T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp62fzp_w6']
[2023-11-20T08:38:36.359+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask retrieve_data
[2023-11-20T08:38:36.436+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-07T00:00:00+00:00 [running]> on host 74ca1234e792
[2023-11-20T08:38:36.530+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-07T00:00:00+00:00'
[2023-11-20T08:38:36.536+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Scripts/etl.py", line 18, in retrieve_data
    aws_access_key_id=YOUR_ACCESS_KEY,
NameError: name 'YOUR_ACCESS_KEY' is not defined
[2023-11-20T08:38:36.563+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231107T000000, start_date=20231120T083836, end_date=20231120T083836
[2023-11-20T08:38:36.581+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task retrieve_data (name 'YOUR_ACCESS_KEY' is not defined; 76)
[2023-11-20T08:38:36.598+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-20T08:38:36.639+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:43:23.098+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-20T08:43:23.105+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-20T08:43:23.106+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:43:23.123+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-07 00:00:00+00:00
[2023-11-20T08:43:23.131+0000] {standard_task_runner.py:57} INFO - Started process 75 to run task
[2023-11-20T08:43:23.136+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-07T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpt44t_bif']
[2023-11-20T08:43:23.142+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask retrieve_data
[2023-11-20T08:43:23.228+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-07T00:00:00+00:00 [running]> on host c84b35a13244
[2023-11-20T08:43:23.304+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-07T00:00:00+00:00'
[2023-11-20T08:43:25.926+0000] {etl.py:60} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T08:43:25.929+0000] {etl.py:64} INFO - Uploading data to 'raw_data'...
[2023-11-20T08:43:26.078+0000] {etl.py:71} INFO - Updating 'Old_Data' with current data...
[2023-11-20T08:43:26.481+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:43:26.496+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231107T000000, start_date=20231120T084323, end_date=20231120T084326
[2023-11-20T08:43:26.554+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:43:26.613+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:46:36.597+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-20T08:46:36.606+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-20T08:46:36.606+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:46:36.620+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-07 00:00:00+00:00
[2023-11-20T08:46:36.626+0000] {standard_task_runner.py:57} INFO - Started process 86 to run task
[2023-11-20T08:46:36.637+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-07T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpo3gl3bhg']
[2023-11-20T08:46:36.645+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask retrieve_data
[2023-11-20T08:46:36.759+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-07T00:00:00+00:00 [running]> on host d26cbef9e8ab
[2023-11-20T08:46:36.865+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-07T00:00:00+00:00'
[2023-11-20T08:46:39.245+0000] {etl.py:62} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T08:46:39.247+0000] {etl.py:66} INFO - Uploading data to 'raw_data'...
[2023-11-20T08:46:41.924+0000] {etl.py:73} INFO - Updating 'Old_Data' with current data...
[2023-11-20T08:46:42.377+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:46:42.404+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231107T000000, start_date=20231120T084636, end_date=20231120T084642
[2023-11-20T08:46:42.594+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:46:42.619+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T08:50:16.687+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-20T08:50:16.711+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-20T08:50:16.714+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T08:50:16.733+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-07 00:00:00+00:00
[2023-11-20T08:50:16.739+0000] {standard_task_runner.py:57} INFO - Started process 77 to run task
[2023-11-20T08:50:16.747+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-07T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp15apne0z']
[2023-11-20T08:50:16.757+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask retrieve_data
[2023-11-20T08:50:16.811+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-07T00:00:00+00:00 [running]> on host 3ef39241d6e6
[2023-11-20T08:50:16.933+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-07T00:00:00+00:00'
[2023-11-20T08:50:18.930+0000] {etl.py:87} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T08:50:18.932+0000] {etl.py:91} INFO - Uploading data to 'raw_data'...
[2023-11-20T08:50:19.097+0000] {etl.py:98} INFO - Updating 'Old_Data' with current data...
[2023-11-20T08:50:20.132+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T08:50:20.147+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231107T000000, start_date=20231120T085016, end_date=20231120T085020
[2023-11-20T08:50:20.222+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T08:50:20.268+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T22:32:24.773+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-20T22:32:24.799+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-20T22:32:24.804+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T22:32:25.106+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-07 00:00:00+00:00
[2023-11-20T22:32:25.124+0000] {standard_task_runner.py:57} INFO - Started process 95 to run task
[2023-11-20T22:32:25.138+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-07T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpvlkvzz34']
[2023-11-20T22:32:25.169+0000] {standard_task_runner.py:85} INFO - Job 72: Subtask retrieve_data
[2023-11-20T22:32:25.372+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-07T00:00:00+00:00 [running]> on host ad6c889005f6
[2023-11-20T22:32:25.513+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-07T00:00:00+00:00'
[2023-11-20T22:32:28.467+0000] {etl.py:87} INFO - No new or updated data to upload. Creating an empty CSV with headers.
[2023-11-20T22:32:28.481+0000] {etl.py:91} INFO - Uploading data to 'raw_data'...
[2023-11-20T22:32:28.643+0000] {etl.py:98} INFO - Updating 'Old_Data' with current data...
[2023-11-20T22:32:29.526+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T22:32:29.558+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231107T000000, start_date=20231120T223224, end_date=20231120T223229
[2023-11-20T22:32:29.616+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T22:32:29.687+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-11-20T22:45:55.306+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-20T22:45:55.368+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-20T22:45:55.378+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T22:45:55.417+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-07 00:00:00+00:00
[2023-11-20T22:45:55.451+0000] {standard_task_runner.py:57} INFO - Started process 95 to run task
[2023-11-20T22:45:55.479+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-07T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp2etrtbl9']
[2023-11-20T22:45:55.509+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask retrieve_data
[2023-11-20T22:45:55.755+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-07T00:00:00+00:00 [running]> on host e1d2c8bc7439
[2023-11-20T22:45:56.197+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-07T00:00:00+00:00'
[2023-11-20T22:45:56.751+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Scripts/etl.py", line 60, in retrieve_data
    objects_to_delete = s3.list_objects_v2(Bucket=BUCKET_NAME, Prefix='raw_data/')
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist
[2023-11-20T22:45:56.799+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231107T000000, start_date=20231120T224555, end_date=20231120T224556
[2023-11-20T22:45:56.826+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task retrieve_data (An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist; 95)
[2023-11-20T22:45:56.866+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-20T22:45:56.936+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-20T22:47:34.333+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-20T22:47:34.376+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-07T00:00:00+00:00 [queued]>
[2023-11-20T22:47:34.377+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-20T22:47:34.483+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_data> on 2023-11-07 00:00:00+00:00
[2023-11-20T22:47:34.502+0000] {standard_task_runner.py:57} INFO - Started process 95 to run task
[2023-11-20T22:47:34.514+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'austin_animal_shelter_dag', 'retrieve_data', 'scheduled__2023-11-07T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpnn1a7i7x']
[2023-11-20T22:47:34.553+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask retrieve_data
[2023-11-20T22:47:34.828+0000] {task_command.py:416} INFO - Running <TaskInstance: austin_animal_shelter_dag.retrieve_data scheduled__2023-11-07T00:00:00+00:00 [running]> on host fda681cc78c9
[2023-11-20T22:47:35.037+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='austin_animal_shelter_dag' AIRFLOW_CTX_TASK_ID='retrieve_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-07T00:00:00+00:00'
[2023-11-20T22:47:36.997+0000] {etl.py:91} INFO - Uploading data to 'raw_data'...
[2023-11-20T22:47:40.626+0000] {etl.py:98} INFO - Updating 'Old_Data' with current data...
[2023-11-20T22:47:41.316+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-20T22:47:41.338+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=austin_animal_shelter_dag, task_id=retrieve_data, execution_date=20231107T000000, start_date=20231120T224734, end_date=20231120T224741
[2023-11-20T22:47:41.385+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-20T22:47:41.424+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
